# Generated by Django 4.2.29 on 2026-03-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_user_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
