# Generated by Django 6.0.3 on 2026-04-25 17:00

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog_bill_historicalbudget_historicalexpense_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalbudget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalbudget',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbudget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialgoal',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialgoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalincome',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalincome',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalincome',
            name='user',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='core_expens_user_id_84343e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='core_expens_user_id_e92993_idx'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='HistoricalBudget',
        ),
        migrations.DeleteModel(
            name='HistoricalExpense',
        ),
        migrations.DeleteModel(
            name='HistoricalFinancialGoal',
        ),
        migrations.DeleteModel(
            name='HistoricalIncome',
        ),
    ]
